accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views

# app_name = 'accounts'
urlpatterns = [
    url(r'^profile/', views.Profile.as_view(), name='profile'),
    url(r'^login/', views.login_view, name='auth_login'),
    url(r'^logout/', auth_views.logout, name='auth_logout'),

    url(r'^_face/$', views.FaceAPIView.as_view(), name='face'),
]

presence_logger/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter
from django.views.generic import TemplateView

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'devices', views.TrackedDeviceViewSet)
router.register(r'entries', views.EntryViewSet)

app_name = 'presence_logger'
urlpatterns = [
    url(r'^dashboard/', views.DashboardView.as_view(), name='dashboard'),
    url(r'^about/', TemplateView.as_view(template_name="presence_logger/about.html"), name='about'),
    url(r'^device/delete/(?P<id>\d+)/$', views.DeviceView.as_view(), name='device-delete'),
    url(r'^device/registration/(?P<id>\d+)/$', views.DeviceRegistrationView.as_view(), name='device-registration'),

    url(r'^api/v1.0/_turris/$', views.EntryAPIView.as_view(), name='entry'),
    url(r'^api/v1.0/_present-users/$', views.PresentUsersAPIView.as_view(), name='present-user'),

    url(r'^api/v1.0/', include(router.urls)),
]

webhook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^google/$', views.GoogleWebhookView.as_view(), name='google-webhook'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    url_face = models.URLField("URL face", blank=True)

    def __str__(self):
        """String representation of model instance."""
        return f' <Profile: {self.user}>'


@receiver(post_save, sender=User)
def create_favorites(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from slacksay import slacksay

from unidecode import unidecode

from presence_logger.models import Device
from . import models

import logging

# Get an instance of a logger
logger = logging.getLogger('nucleus_hub')


def login_view(request):
    return render(request, 'accounts/login.html', {'next': request.GET['next']})


@method_decorator(login_required, name='dispatch')
class Profile(View):
    template_name = 'accounts/profile.html'

    def get(self, request):
        context = {
            'ipv4_address': request.META['REMOTE_ADDR'],
            'devices': Device.objects.filter(user=request.user),
            'profile': models.Profile.objects.get(user=request.user),

        }

        return render(request, self.template_name, context=context)


class FaceAPIView(APIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        name = request.GET['name']
        url = request.GET['link']

        profiles = models.Profile.objects.all()

        if name == 'unknown':
            slacksay.cctv(url)
            return Response({'message': 'CCTV image sent'}, status=status.HTTP_200_OK)

        for profile in profiles:
            user = profile.user
            fullname = user.first_name + "_" + user.last_name
            fullname = unidecode(fullname)
            if fullname == name:
                profile.url_face = url
                profile.save()

                # Send to Slack
                slacksay.photo(url, fullname)

                return Response({'message': 'URL successfully saved.'}, status=status.HTTP_200_OK)

        return Response({'message': f'User {name} not found.'}, status=status.HTTP_404_NOT_FOUND)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="text-center">
        <br/>
        <h3>Please log in using your Google account</h3>
        <br/>
        <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ next }}" class="btn btn-outline-dark">
            <img src="{% static 'accounts/img/google_logo.png' %}">
            Sign in with Google
        </a>
    </div>

{% endblock %}

accounts/templates/accounts/navbar.html
{% load static %}
{% if request.user.is_authenticated %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="dropdown01" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }} {{ request.user.last_name }}</a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">

            {% if request.user.is_superuser %}
                <h6 class="dropdown-header">Administration</h6>
                <a class="dropdown-item"
                   href="{% url 'admin:index' %}">Admin</a>
                <div class="dropdown-divider"></div>
            {% endif %}

            <h6 class="dropdown-header">Profile</h6>
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'auth_logout' %}">Logout</a>


        </div>
    </li>
{% else %}
    <!--
    <form class="form-inline " method="POST" action="{% url 'auth_login' %}">
        {% csrf_token %}
        <div class="form-group my-2 my-lg-0">
            <input type='text' class='form-control mr-sm-2' name="username" placeholder="Username">
            <input type='password' class='form-control mr-sm-2' name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-outline-success my-2 my-sm-0 mr-sm-2">Sign In</button>

    </form>
    -->
    <div class="container">
        <a href="{% url 'social:begin' 'google-oauth2' %}">
            <img class="btn btn-light" src="{% static 'accounts/img/google_logo.png' %}" width="45" height="38">
        </a>
    </div>
{% endif %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Profile
{% endblock %}

{% block content %}

    {% if messages %}

        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success" role="alert">
                    <strong>Well done!</strong> {{ message }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    <strong>Failed!</strong> {{ message }}
                </div>
            {% endif %}
        {% endfor %}

    {% endif %}

    <h1>Profile</h1>
    <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-4"></div>
    </div>

    <h2>User information:</h2>
    <div class="row">
        <div class="col-md-6">
            <br>
            <div class="form-group row">
                <div class="col-sm-3">
                    <label for="inputFirstName"><b>First name:</b></label>
                </div>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="inputFirstName" aria-describedby="Your first name"
                           placeholder="{{ request.user.first_name }}" disabled>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <label for="inputLastName"><b>Last name:</b></label>
                </div>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="inputLastName" aria-describedby="Your last name"
                           placeholder="{{ request.user.last_name }}" disabled>
                </div>


            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <label for="inputEmail"><b>Email:</b></label>
                </div>
                <div class="col-sm-9">
                    <input type="email" class="form-control" id="inputEmailName" aria-describedby="Your email address"
                           placeholder="{{ request.user.email }}" disabled>
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.
                    </small>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="text-center">
                {% if profile.url_face %}
                    <img src="{{ profile.url_face }}" class="rounded mx-auto d-block" height="250"
                         width="250">
                {% else %}
                    <img src="{% static 'accounts/img/profile_pic.png' %}" class="rounded mx-auto d-block" height="250"
                         width="250">
                {% endif %}
            </div>
        </div>
    </div>

    <h2>Devices:</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Current device</h4>
                        <h6 class="card-subtitle mb-2 text-muted">Device information</h6>
                        <p class="card-text">
                            <b>IPv4 address: </b>{{ ipv4_address }}<br>
                            Please check if you are connected to Wi-Fi '<b>Turris</b>'.
                        </p>
                        <div class="text-right">
                            <button type="button" class="btn btn-success"
                                    onclick="registration({{ request.user.id }})">Register this device
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-5">
                <table id="device-table" class="table table-bordered table-hover table-sm">
                    <thead class="thead-default">
                    <tr>
                        <th>ID</th>
                        <th>MAC address</th>
                        <th>Action(s)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for device in devices %}
                        <tr id="device-table-row">
                            <th scope="row">{{ device.id }}</th>
                            <td>{{ device.mac_address }}</td>
                            <td>
                                <a data-method="delete" href="{% url 'presence_logger:device-delete' id=device.id %}"
                                   class="btn btn-danger btn-sm"
                                   rel="nofollow">Remove</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static 'accounts/js/registration.js' %}"></script>
{% endblock %}