presence_logger/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter
from django.views.generic import TemplateView

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'devices', views.TrackedDeviceViewSet)
router.register(r'entries', views.EntryViewSet)

app_name = 'presence_logger'
urlpatterns = [
    url(r'^dashboard/', views.DashboardView.as_view(), name='dashboard'),
    url(r'^about/', TemplateView.as_view(template_name="presence_logger/about.html"), name='about'),
    url(r'^device/delete/(?P<id>\d+)/$', views.DeviceView.as_view(), name='device-delete'),
    url(r'^device/registration/(?P<id>\d+)/$', views.DeviceRegistrationView.as_view(), name='device-registration'),

    url(r'^api/v1.0/_turris/$', views.EntryAPIView.as_view(), name='entry'),
    url(r'^api/v1.0/_present-users/$', views.PresentUsersAPIView.as_view(), name='present-user'),

    url(r'^api/v1.0/', include(router.urls)),
]

webhook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^google/$', views.GoogleWebhookView.as_view(), name='google-webhook'),
]

presence_logger/models.py
from django.db import models
from django.contrib.auth.models import User


class Device(models.Model):
    """Represent device.

    Each device is identify by its MAC address and is join with maximal one user instance.

   Attributes:
       user (ForeignKey, optional): Foreign key to Django User model
       mac_address (CharField): MAC address of device
    """
    user = models.ForeignKey(User, related_name='devices', null=True, blank=True, on_delete=models.CASCADE)
    mac_address = models.CharField(max_length=17, unique=True)

    class Meta:
        ordering = ['-user']

    def __str__(self):
        """String representation of model instance."""
        return f'<User: {self.user}; MAC: {self.mac_address}>'


class Entry(models.Model):
    """Represent row in ARP table.

    Each row in ARP table is used to identify whether device was in certain time connected to the AC.
    Attributes:
        timestamp (DateTimeField): Timestamp of entry automatically generated
        is_connected(BooleanField): State of device
        device (ForeigKey): Foreign key to device instance
        ipv4_address (CharField, optional): IPv4 address for current time and device
        ipv6_address (CharField, optional): IPv6 address for current time and device
    """
    device = models.OneToOneField(Device, on_delete=models.CASCADE, primary_key=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_connected = models.BooleanField()
    ipv4_address = models.CharField(max_length=15, null=True, blank=True)
    ipv6_address = models.CharField(max_length=45, null=True, blank=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name_plural = 'Entries'

    def __str__(self):
        """String representation of model instance."""
        return f'<TIMESTAMP: {self.timestamp}; MAC: {self.device}; IPv4: {self.ipv4_address}>'

presence_logger/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib.auth.models import User
from django.db.models import Count, Case, When, IntegerField
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework import status, viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated

from .models import Device, Entry
from . import serializers
from . import exception

from python_arptable import get_arp_table

import logging

# Get an instance of a logger
logger = logging.getLogger('nucleus_hub')


@method_decorator(login_required, name='dispatch')
class DashboardView(View):
    """Index view for presence_logger application."""
    template_name = 'presence_logger/dashboard.html'

    def get(self, request):
        logger.info('Something went wrong!')
        # Cookies handling
        refresh_time = request.COOKIES.get('refresh_time')
        try:
            refresh_time = int(refresh_time)
        except (ValueError, TypeError):
            refresh_time = 5

        context = {
            'present_users': User.objects.exclude(devices=None).filter(
                devices__entry__is_connected=True).annotate(
                active_devices=Count(Case(
                    When(devices__entry__is_connected=True, then=1),
                    default=0, output_field=IntegerField()
                ))),
            'absent_users': User.objects.exclude(devices=None).exclude(devices__entry__is_connected=True).distinct(),
            'refresh_times': [1, 5, 10, 15],
            'refresh_time': refresh_time

        }
        return render(request, self.template_name, context=context)


class DeviceView(LoginRequiredMixin, View):
    def get(self, request, id):
        device = get_object_or_404(Device, pk=id)

        if device.user != request.user:
            messages.error(request, "You haven't rights to to that, Sir!")
            return redirect('profile')

        device.user = None
        device.save()
        messages.success(request, "Device was successfully deleted.")

        return redirect('profile')


""" REST API views
########################################################################################################################
"""

"""
Browsable API
#############
"""


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """APIView for list User instances."""
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = serializers.UserHyperlinkedSerializer


class TrackedDeviceViewSet(viewsets.ReadOnlyModelViewSet):
    """APIView for list Device instances."""
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Device.objects.all()
    serializer_class = serializers.DeviceHyperlinkedSerializer


class EntryViewSet(viewsets.ReadOnlyModelViewSet):
    """APIView for list EntryAPIView instances."""
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)
    queryset = Entry.objects.all()
    serializer_class = serializers.EntryHyperlinkedSerializer


"""
Regular API
###########
"""


class EntryAPIView(APIView):
    """APIView for receive data from turris."""
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def post(self, request, format=None):
        serializer = serializers.EntrySerializer(data=request.data, many=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, format=None):
        entries = Entry.objects.all()

        for entry in entries:
            entry.is_connected = False
            entry.save()

        return Response({"status": "deleted"}, status=status.HTTP_200_OK)


class PresentUsersAPIView(APIView):
    """APIView for get active user. Used by javascript."""

    def get(self, request):
        # In parameters must be dictionary, otherwise empty dictionary will be return
        serializer = serializers.PresentUsersSerializer({})
        return Response(serializer.data)


class DeviceRegistrationView(APIView):
    """APIView for registration new devices for user. Do not use permission_classes nor authentication_classes."""

    def get(self, request, id):
        try:
            mac_address = self.get_mac_address(request)
        except exception.MACAddressError:
            return Response({
                "message": "Can't resolve MAC address. Please check if you are connected to the Wi-Fi <b>Turris</b>.",
                "class": "alert-danger",
            }, status=status.HTTP_400_BAD_REQUEST)

        try:
            user = User.objects.get(pk=id)
        except User.DoesNotExist:
            return Response({
                "message": "User with this `id` doesn't exists.",
                "class": "alert-danger",
            }, status=status.HTTP_400_BAD_REQUEST)

        try:
            device = Device.objects.get(mac_address=mac_address)
            if device.user is not None:
                return Response({
                    "message": "This device is already taken.",
                    "class": "alert-info",
                }, status=status.HTTP_400_BAD_REQUEST)

            device.user = user
        except Device.DoesNotExist:
            device = Device.objects.create(mac_address=mac_address, user=user)

        device.save()

        return Response({
            "message": "Device was successfully registered.",
            "class": "alert-success",
        }, status=status.HTTP_200_OK)

    @classmethod
    def get_mac_address(cls, request):
        mac_address = None
        ipv4_address = request.META['REMOTE_ADDR']

        for entry in get_arp_table():
            if entry["IP address"] == ipv4_address:
                mac_address = entry["HW address"]

        if mac_address is None:
            raise exception.MACAddressError()

        return mac_address

presence_logger/templates/presence_logger/about.html
{% extends 'presence_logger/base.html' %}

{% block title %}
    About
{% endblock %}

{% block page %}
    <div class="row-space">
        <h2>Turris - starpin</h2>
        An app called "starpin" (STealthy ARP INformer) written in Ruby is running on the Turris access point
        as a service. This app observes the list of wirelessly connected devices (it used to be the ARP table)
        and notifies the Hub about any changes via a REST API. starpin is set to start upon boot. It supports logging
        and is controllable via the /etc/init.d/starpin script. It can recover from connection losses and resets the
        session automatically after a preset interval to prevent any long-time desynchronization.
    </div>

    <div class="row-space">
        <h2>Server</h2>
        A web application called "Nucleus Hub" (written in Python using the Django framework) running on a Raspberry Pi 3
        serves as a hub for the
        connected services. It receives data from the starpin utility and uses them to evaluate the current state of
        the network (connected devices). It supports authentication via OAuth and allows users to
        sign in with their Google accounts. After the registration every user is able to register their devices via the
        builtin registration mechanism, which ties the MAC address of the device to the user's account. This can be then
        used to determine whether a user is present.
        Nucleus Hub also exposes an API to the eClub Camera and is able to match received pictures (recognized by AWS)
        with the Hub users.
    </div>

    <div class="row-space">
        <h2>Diagram</h2>

             class="img-fluid">
    </div>

    <div class="row-space">
        <h2>Futures ideas</h2>
        TODO
    </div>

    <div class="row-space">
        <h2>Codes</h2>
        All our codes are open-source under MIT licence and you can access them on our <a
            href="https://gitlab.com/eclubiot">Gitlab</a>
    </div>
{% endblock %}

presence_logger/templates/presence_logger/base.html
{% extends 'base.html' %}

{% block content %}
    {% block page %} {% endblock %}
{% endblock %}

presence_logger/templates/presence_logger/dashboard.html
{% extends 'presence_logger/base.html' %}
{% block title %}
    Dashboard
{% endblock %}

{% block page %}
    {% load static %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Present users:</h2>
                <p class="lead">
                    Currently present club's users.
                </p>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="container text-right">
                        {% include 'presence_logger/refresh_times.html' %}
                    </div>
                </div>
                <div class="row">
                    <div class="container text-right">
                        <p class="lead" id="clock"></p>
                    </div>
                </div>

            </div>
        </div>
        <table id="presence-table" class="table table-striped table-sm">
            <thead class="thead-default">
            <tr>
                <th>#</th>
                <th>Fullname</th>
                <th>Active device(s)</th>
                <th>Last photo</th>

            </tr>
            </thead>
            <tbody>
            {% for present_user in present_users %}
                <tr id="presence-table-row">
                    <th scope="row">
                        <i class="material-icons" style="color:#75ff33">tag_faces</i>
                    </th>
                    <td>{{ present_user.first_name }} {{ present_user.last_name }}</td>
                    <td>{{ present_user.active_devices }}</td>
                    {% if present_user.profile.url_face %}
                        <td><a href="{{ present_user.profile.url_face }}">Link</a></td>
                    {% else %}
                        <td></td>
                    {% endif %}
                </tr>
            {% endfor %}
            {% for absent_user in absent_users %}
                <tr id="presence-table-row">
                    <th scope="row">
                        <i class="material-icons" style="color:#f44336">face</i>
                    </th>
                    <td>{{ absent_user.first_name }} {{ absent_user.last_name }}</td>
                    <td>{{ absent_user.active_devices }}</td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block javascripts %}
    <!-- Main js support -->
    <script src="{% static 'presence_logger/js/auto_refresh.js' %}"></script>

    <script type=text/javascript>
        $(start_time());
        $(update_refresh_time());
        $(update_tables());
    </script>
{% endblock %}

presence_logger/templates/presence_logger/navbar.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle {% if "presence-logger" in request.path %} active {% endif %}"
       id="dropdown01" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">Presence-logger</a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
        <a class="dropdown-item {% if "presence-logger/dashboard" in request.path %} active {% endif %}"
           href="{% url 'presence_logger:dashboard' %}">Dashboard</a>
        <a class="dropdown-item" href="{% url 'presence_logger:api-root' %}">Browsable API</a>
        <a class="dropdown-item {% if "presence-logger/about" in request.path %} active {% endif %}"
           href="{% url 'presence_logger:about' %}">About</a>
    </div>
</li>

presence_logger/templates/presence_logger/refresh_times.html
<div class="btn-group" data-toggle="buttons" id="time" onchange="select_refresh_time()">
    {% for time in refresh_times %}
        <label class="btn
                            {% if time == refresh_time %}
                                btn-primary active
                            {% else %}
                                btn-secondary
                            {% endif %}
                            " id="time-select-label-{{ time }}">
            <input type="radio"
                   name="time-select"
                   id="time-select-{{ time }}"
                   autocomplete="off"
                   value="{{ time }}"
                    {% if time == refresh_time %}
                   checked
                    {% endif %}
            >
            {{ time }}s
        </label>
    {% endfor %}
</div>